name: Changelog
on:
  push:
    branches:
      - main
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v5
      with:
        github-token: ${{ secrets.github_token }}
        skip-git-pull: "true"
        release-count: 0
        skip-on-empty: false

  publish:
    needs: changelog
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - run: git checkout main
    - run: git pull
    - run: npm install
    - run: npm run build
    - run: npm config set registry https://registry.npmjs.org 
    - run: npm config set _authToken=${{ secrets.NPM_TOKEN }}
    - run: npm config fix
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
