name: Changelog
on:
  push:
    branches:
      - main
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.github_token }}
        skip-git-pull: "true"
        release-count: 0
        skip-on-empty: false

  publish:
    needs: changelog
    runs-on: ubuntu-latest

    steps:
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '120s'

    - uses: actions/checkout@v3
    - name: Use Node.js latest
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - run: npm install
    - run: npm run build
    - run: npm config set registry https://registry.npmjs.org 
    - run: npm config set _authToken=${{ secrets.NPM_TOKEN }}
    - run: npm config fix
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
